### Sign-up as a new user
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "username": "celld",
  "password": "connarde",
  "email": "adrienleblanc53@gmail.com",
  "role": "ROLE_USER"
}

###

### Sign-up as a new user
POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
  "username": "celld",
  "password": "connarde"
}

###